### ISSUE TITLE
KST Lib now non-compliant with iTunes binary upload checks

### ISSUE THREAD

**Issue by Seoras** [kstechnologies/NIRScanNano_iOS#1] opened 2016-10-03 01:50 UTC
The KST Library is now non-compliant with Apple iTunes binary submission due to the error:

> Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key

The solution is the one given in this forum thread:

https://forums.developer.apple.com/thread/62261

as I can find the offending string 

> <string>iPhoneSimulator</string>

in :
KSTSpectrumLibrary.framework/Info.plist

**Comment by bobkressin** [comment] 2016-10-04 14:20
Thank you for submitting this, @Seoras . It seems to be part of our old HockeyApp SDK we had embedded; we've since moved on to using Apple's TestFlight. I'll remove HockeyApp altogether, recompile, and submit an update to iTunes Connect to make sure the issue is resolved.

**Comment by bobkressin** [comment] 2016-10-04 23:08
Fixed in `d6760ce`

**Closed as completed by bobkressin** 2016-10-04 23:08 UTC
